from django.core.exceptions import ValidationError

def local_file_validatorX(file):
    print("Local file validator running")
