from django.core.exceptions import ValidationError

def local_file_validator(file):
    print("Local file validator running")
