from django.core.exceptions import ValidationError

def global_file_validator(file):
    print("Global validator running")
